In [2]:
import pandas as pd

In [4]:
# reading the csv files
df_exams = pd.read_csv('/Users/vic/Downloads/StudentsPerformance.csv')
df_exams.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

# 1 Adding a new column

## 1.1 Adding a new column with a scalar value

In [9]:
# adding a new column to a dataframe
df_exams['language score'] = 70
df_exams

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  \
0                      none          72             72             74   
1                 completed          69             90             88   
2                      none          90             95             93   
3                      none          47             57             44   
4                      none          76             78             75   
..                      ...         ...            ...            ...   
995               completed          88             99             95   
996                    none          62             55             55   
997               completed          59             71             65   
998               completed          68             78             77   
999                    none          77             86             86   

     language score  
0                70  
1                70  
2                70  
3                70  
4                70  
..              ...  
995              70  
996              70  
997              70  
998              70  
999              70  

[1000 rows x 9 columns]

## 1.2 Adding a new column with an array

The dataframe has 1000 rows, so we need to create an array with 1000 elements

In [18]:
# Import numpy
import numpy as np

In [20]:
# Create an array of 1000 elements
np.arange(0, 1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [22]:
# assign to a column
language_score = np.arange(0, 1000)

In [24]:
# length of the array
len(language_score)

1000

In [26]:
# adding a new column to dataframe with an array
df_exams['language score'] = language_score
df_exams

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  \
0                      none          72             72             74   
1                 completed          69             90             88   
2                      none          90             95             93   
3                      none          47             57             44   
4                      none          76             78             75   
..                      ...         ...            ...            ...   
995               completed          88             99             95   
996                    none          62             55             55   
997               completed          59             71             65   
998               completed          68             78             77   
999                    none          77             86             86   

     language score  
0                 0  
1                 1  
2                 2  
3                 3  
4                 4  
..              ...  
995             995  
996             996  
997             997  
998             998  
999             999  

[1000 rows x 9 columns]

In [28]:
# create random integer numbers between 1 and 100
np.random.randint(1, 100, size=1000)

array([73, 55,  4, 82, 88, 33, 83, 93, 42, 57, 73, 73, 29, 17, 31, 83, 62,
        5, 50, 32, 91, 86, 17, 46, 18, 33, 73, 69, 55, 64, 90, 49, 45, 90,
       34, 67, 96, 48, 24, 19, 75, 23,  1, 16, 75, 16, 58, 32, 71, 73, 69,
       50, 71, 38, 54, 79, 78, 48, 66, 76, 16, 32, 65, 72, 72, 55, 19, 83,
       29, 70,  5, 25, 72, 77, 96, 54, 74, 21, 19, 54,  6, 47, 54, 19, 27,
       64, 60, 48,  5, 46, 32, 95, 83, 61, 79, 82, 57, 67, 94, 97, 56,  6,
       10, 34, 70, 64, 15, 25, 18,  7, 61,  8, 57, 47, 16, 31, 67, 41, 46,
       57, 37,  2, 17, 99, 39, 84, 17, 46,  6, 44, 65, 42, 77, 10, 98, 23,
       89, 47, 91, 82, 47, 46, 82, 31, 53, 65,  5,  6, 95,  9, 24, 73, 90,
       74,  5, 18, 54, 68, 80, 32,  2, 43, 10, 13, 74, 45, 75,  6, 20, 35,
       15, 21, 48, 80, 44, 22, 96, 14, 76, 88, 17, 20, 21, 90, 97, 57, 69,
       79, 28, 44, 77, 24, 39, 21, 37,  9, 56, 17, 26, 21, 64, 23, 30, 28,
       66, 54, 20, 52, 11, 14, 68, 61, 62, 28,  5, 25, 47, 11, 39, 81, 60,
       59, 74, 23, 32, 56

In [30]:
# new variable
int_language_score = np.random.randint(1, 100, size=1000)

In [32]:
# min value inclusive and high value exclusive
min(int_language_score)
max(int_language_score)

99

In [36]:
# adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  \
0                      none          72             72             74   
1                 completed          69             90             88   
2                      none          90             95             93   
3                      none          47             57             44   
4                      none          76             78             75   
..                      ...         ...            ...            ...   
995               completed          88             99             95   
996                    none          62             55             55   
997               completed          59             71             65   
998               completed          68             78             77   
999                    none          77             86             86   

     language score  
0                99  
1                27  
2                43  
3                 5  
4                40  
..              ...  
995              73  
996               3  
997              56  
998              33  
999              63  

[1000 rows x 9 columns]

In [38]:
# creating random float numbers between 1 and 100
np.random.uniform(1, 100, size=1000)

array([91.98434107, 46.41608746, 50.20149284, 74.01869943, 38.01906909,
       84.37600095,  7.41082939, 43.21940714, 26.08133679, 20.77595756,
       37.55726333, 28.29367292, 71.00344528, 27.51136615, 56.14854317,
       28.44320772,  2.2907668 , 80.63720381, 69.05607239,  1.1018591 ,
       39.54389836, 39.7810552 , 70.28087949, 72.61109021, 62.48321311,
        7.92805487, 68.96722853, 41.96890068, 10.61762802, 30.38537585,
       12.631953  , 12.51650873, 23.16757016, 13.50444488, 26.27008783,
       29.11556566, 10.52863019, 83.72862149, 10.80359103, 84.83668425,
       67.39666003, 83.2106328 , 35.67331221, 80.44390754,  2.6516912 ,
       37.11349433, 13.18383182, 37.84060859, 19.41185509, 61.17081533,
       80.08850652, 57.21454223,  3.84081685, 22.57613037, 59.74897175,
       61.63688618, 72.62856298, 57.43802452, 18.30874289, 33.27981009,
       56.46061498, 87.88612872, 54.87336177, 51.13323167, 59.62339417,
        9.45888934, 67.19949065, 18.35355495, 67.7438036 , 69.85